### ISSUE TITLE
I can't run the client app for more than 1 hour

### ISSUE THREAD

**Issue by mariebehzadi** [cattr-app/desktop-application#1]
Hi, 
I've used your app and it seems to be very useful so well done. the only problem i have so far is that i can't work more than 1 hour on any task. if so, i will get an error like this 

**Error: Length of interval must be less than an hour**

the time duration won't be uploaded to my server and it will fail to take a screen capture. any suggestions in order to fix this??

**Comment by amazing-cat** [comment]
Hello. This problem is caused by the settings of the users in Cattr. There is a field "Screenshot interval" that allows set interval in minutes, so you can easily reduce the interval to make it less than an hour. If you'll reduce it, it should solve the issue.
😃
