### ISSUE TITLE
MacOS Catalina version keeps crashing

### ISSUE THREAD

**Issue by hitdependency** [cattr-app/desktop-application#2]
Breaks every 5-15 minutes in random gap,

![image](https://user-images.githubusercontent.com/20301885/79682433-e88ccb80-822a-11ea-977c-85ed50268f69.png)

**Comment by amazing-cat** [comment]
Can you provide the logs of the application?
They are stored under `~/Library/Application\ Support/cattr/logs`.
Please, choose a log file that can contain time gaps when do errors occurred.

**Comment by systryonka** [comment]
Well from now I gave cattr.app full disk access, I will write if it helps

[D] [2020-04-19T09:07:35.816Z] [Database] Database successfully initliazed
[D] [2020-04-19T09:07:35.821Z] [Router] Starting routes load
[D] [2020-04-19T09:07:36.135Z] [Router:Authentication] Loaded
[D] [2020-04-19T09:07:37.033Z] [UserPreferences] Preferences file detected, trying to read
[D] [2020-04-19T09:07:37.035Z] [UserPreferences] Preferences file successfully read
[D] [2020-04-19T09:07:37.035Z] [Router:Miscellaneous] Loaded
[D] [2020-04-19T09:07:37.036Z] [Router:Projects] Loaded
[D] [2020-04-19T09:07:37.036Z] [Router:Tracking] Loaded
[D] [2020-04-19T09:07:37.036Z] [Router:Tasks] Loaded
[D] [2020-04-19T09:07:37.036Z] [Router:Time] Loaded
[D] [2020-04-19T09:07:37.037Z] [Router:Trasnlation] Loaded
[D] [2020-04-19T09:07:37.037Z] [Router:UserPreferences] Loaded
[D] [2020-04-19T09:07:37.128Z] [Screen-Notifier] Loaded
[D] [2020-04-19T09:07:37.247Z] [Tray] Loaded
[D] [2020-04-19T09:07:37.248Z] [PowerManager] Loaded
[D] [2020-04-19T09:07:37.682Z] [Keychain] Fetched saved credentials from system keychain
[D] [2020-04-19T09:07:38.152Z] [Router:Projects] Projects sync initiated by renderer
[D] [2020-04-19T09:07:38.453Z] [Router:Projects] Projects successfully synced
[D] [2020-04-19T09:07:38.454Z] [Router:Tasks] Tasks sync initiated by renderer
[D] [2020-04-19T09:07:38.746Z] [Controller:Tasks] Task-to-project relations remapping started
[D] [2020-04-19T09:07:38.754Z] [Controller:Tasks] Task-to-Projects mappings successfully updated
[D] [2020-04-19T09:07:38.754Z] [Controller:Time] Starting syncing time per task values
[D] [2020-04-19T09:07:39.033Z] [Controller:Time] Finished syncing time per task values
[D] [2020-04-19T09:07:39.196Z] [Router:Tasks] Tasks successfully synced
[D] [2020-04-19T09:08:01.855Z] [TaskTracker] Started tracking task "XXX XXXXXX" (period duration is 590s)
[D] [2020-04-19T09:08:01.982Z] [PowerManager] Prevent display sleep while tracking!
[D] [2020-04-19T09:10:59.248Z] [TaskTracker] Stops task tracking (push = ok, event = ok)
[D] [2020-04-19T09:10:59.249Z] [TaskTracker] Capturing interval: 2020-04-19T09:08:03.249Z ~ 2020-04-19T09:10:59.249Z (duration: 176 ticks)
[D] [2020-04-19T09:10:59.265Z] [Controller:Time] Updated track for task (1bdc292a-ac22-4d3e-bdad-9715be0XXXXX): 200s (delta = +176s)
[D] [2020-04-19T09:10:59.265Z] [TaskTracker] Track time is updated (+176 ticks)
[D] [2020-04-19T09:11:02.677Z] [TaskTracker] Screenshot was made
[E] [2020-04-19T09:11:03.504Z] [Controller:Time-Intervals] (APIundefined) Error during interval & screenshot push: Error: The "" file does not exist or is not readable.
<BEGIN STACK TRACE>
    at Object.e.exports.pushTimeIntervalAndScreenshot (/Applications/Cattr.app/Contents/Resources/app.asar/app.js:1:28764)
<END STACK TRACE>
[E] [2020-04-19T09:11:03.505Z] [TaskTracker] (APIundefined) Error occured during the interval submit: Error: The "" file does not exist or is not readable.
<BEGIN STACK TRACE>
    at Object.captureInterval (/Applications/Cattr.app/Contents/Resources/app.asar/app.js:1:22591)
<END STACK TRACE>
[E] [2020-04-19T09:11:03.505Z] [TaskTracker] (APIundefined) Error occured during the interval submit: Error: The "" file does not exist or is not readable.
<BEGIN STACK TRACE>
    at Object.captureInterval (/Applications/Cattr.app/Contents/Resources/app.asar/app.js:1:22591)
<END STACK TRACE>

**Comment by systryonka** [comment]
But I don't think the bottom error is the reason, because I can't see it in previous logs. When error occurres log ends.

**Comment by systryonka** [comment]
![image](https://user-images.githubusercontent.com/20301885/79684390-9a32f900-8239-11ea-9ef0-c6f0b1d65ab1.png)

If I should keep it english way - tell me.
Напишу на русском, так как ваша команда, вроде как, из спб. 
Часто вылетает приложение, но в логах это никак не отображается. Время на сервер трекается, синхронизируется и скриншоты добавляются. Сейчас увидел пустое сообщение "Whoops!" и после этого перестал работать таймер - опять помог только перезапуск.

**Comment by systryonka** [comment]
Один раз получилось протрекать время целый час без ошибок, поэтому идей особо нет. Приложение не сворачиваю, мак в сон не увожу, просто запускаю таймер по кнопке.

**Comment by systryonka** [comment]
Well, I figured out reason for the crash - when I use any of volume keys on my mac. Can't test it on another one, this is odd btw

**Comment by amazing-cat** [comment]
Лучше продолжить на английском, дабы люди могли находить решение подобных проблем.

Error in the log you send doesn't relate to disk access.

It occurs due to NGINX config and can be related to proxy config settings or our Docker configuration. We already faced it in our development.

When you send the large screenshot file (screenshot of the display with very high resolution or multiple displays) Nginx doesn't pass the entire file to PHP backend due to buffer settings, so backend doesn't receive screenshot. We already investigate that issue and will update configs with the optimal solution soon.

But this problem shouldn't lead to the crash of the client.

You can try to kill your client, flush `~/Library/Application\ Support/cattr` folder and then launch Cattr again.

**Comment by amazing-cat** [comment]
Hmm. At my mac pressing volume keys crashes client too. I'll create a ticket for developers.

> Well, I figured out reason for the crash - when I use any of volume keys on my mac. Can't test it on another one, this is odd btw

Hmm. At my mac pressing volume keys crashes client too. I'll create a ticket for developers.

**Comment by amazing-cat** [comment]
@hitdependency in the latest committed version (2.4.0-exp...d) we've temporarily disabled IOHook until resolution of [this](https://github.com/wilix-team/iohook/issues/241) issue.

We're expecting to release a production 2.4.0 build on the next week, so stay tuned for the updates!

**Comment by imcatwhocode** [comment]
This issue is not actual anymore due to removing iohook as a dependency to track input devices' activity.
