### ISSUE TITLE
Cattr 3.0.0-RC6 Login failed Invalid email or password

### ISSUE THREAD

**Issue by lexcorp** [cattr-app/desktop-application#35]
Server = Last version 
Client = Cattr 3.0.0-RC6

When try login in desktop application I get this messages:

Login failed
Invalid email or password

![image](https://github.com/cattr-app/desktop-application/assets/5751288/a061d1fe-eda1-4808-91aa-960f98d29309)

In web application I login successfully.

**Comment by aVyarvelsky** [comment]
Attach logs, please

**Comment by lexcorp** [comment]
I solve this by compiling and building the latest version of cattr desktop 3.0.0-RC10.

**Comment by lexcorp** [comment]
> Attach logs, please

Does the desktop application generate a log? or do you mean the nginx log?

**Comment by aVyarvelsky** [comment]
Yes. This error looks like related to Cattr core and Cattr client mismatch.

**Comment by lexcorp** [comment]
> Yes. This error looks like related to Cattr core and Cattr client mismatch.

@aVyarvelsky I compile and build cattr desktop application version 3.0.0-RC10 and if it allows me to enter without errors.

![image](https://github.com/cattr-app/desktop-application/assets/5751288/7030272e-c3bf-42cd-bc8a-4c8a4bced788)

![image](https://github.com/cattr-app/desktop-application/assets/5751288/8fdb1242-f50d-4ed6-9489-4ef18a6fc17b)

![image](https://github.com/cattr-app/desktop-application/assets/5751288/df71f55b-ba55-43d1-8193-ad13d69ded6f)

![image](https://github.com/cattr-app/desktop-application/assets/5751288/bb24fc1e-f4b0-462a-ba10-752b048d4576)

![image](https://github.com/cattr-app/desktop-application/assets/5751288/f82437ad-54fb-42af-834a-37d8e61b1fd6)

**Comment by rajeshisnepali** [comment]
![image](https://github.com/cattr-app/desktop-application/assets/23610013/07035735-4f47-4a53-95aa-e5bbcd338f78)

Even with https://github.com/cattr-app/desktop-application/releases/tag/v3.0.0-RC6

**Comment by lexcorp** [comment]
Hi @rajeshisnepali , use yarn instead of npm. for all commands.

example: yarn install instead npm install

**Comment by DanilShapilov** [comment]
@rajeshisnepali will close your issue, 
We currently don't have working CD for [cattr.app](https://cattr.app/) website.  
Here is the latest version of the app v3.0.0-RC10 at out GitLab:

Linux: https://git.amazingcat.net/cattr/desktop/desktop-application/-/jobs/13523/artifacts/browse/target/

Mac: https://git.amazingcat.net/cattr/desktop/desktop-application/-/jobs/13524/artifacts/browse/target/

Windows: https://git.amazingcat.net/cattr/desktop/desktop-application/-/jobs/13556/artifacts/browse/target/

As for your build errors it can be anything, node-gyp version, nodejs version, OS libraries, python version idk...  
Try to use nodejs 14.19.0, maybe it will help.

**Comment by DanilShapilov** [comment]
@rajesh-neputer please use latest version. https://github.com/cattr-app/server-application/issues/111#issuecomment-1630575155

**Comment by DanilShapilov** [comment]
@rajeshisnepali I'm talking about backend.
