### ISSUE TITLE
Cattr 3.0.0-RC6 how to view log files?

### ISSUE THREAD

**Issue by lexcorp** [cattr-app/desktop-application#36]
Cattr desktop application 3.0.0-RC6, Is it possible to see the error logs?

Or does it generate error logs?

**Comment by aVyarvelsky** [comment]
Windows:
`C:\Users\%username%\AppData\Local\cattr\logs`
`C:\Users\%username%\AppData\Roaming\cattr\logs`
Linux:
`~/.config/cattr/logs`
MacOS:
`~/Libraries/Application\ Support/cattr/logs`
