### ISSUE TITLE
User remains inactive on the front-end's who's online status (green dot on the user's avatar)

### ISSUE THREAD

**Issue by janfar2008** [cattr-app/desktop-application#4]
The user remains inactive on the front-end's who's the online status (green dot on the user's avatar) after the user resumes to work.

**Comment by aVyarvelsky** [comment]
Currently, Cattr calculates user online only based on their intervals. So if your user sent an interval  5-10 minutes ago - he is marked as online.

But we are working on that feature now and in future releases, it will be a beacon-like system. Currently, we almost finished the backend part and now desktop part left.

**Comment by imcatwhocode** [comment]
Heartbeat-based online status implemented in actual builds of Core and Desktop applications.
