### ISSUE TITLE
Error on Install dependencies

### ISSUE THREAD

**Issue by Jao8** [cattr-app/desktop-application#40]
When I run `npm install` its returns the following error

```sh
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@cattr%2fnode - Not found
npm ERR! 404
npm ERR! 404  '@cattr/node@^4.0.0-RC4' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

```

Anyone can help with this?

I found this package on npmjs [@amazingcat/node-cattr](https://www.npmjs.com/package/@amazingcat/node-cattr), it is compatible?

**Comment by lexcorp** [comment]
Hi @Jao8, try using yarn instead of npm to all commands, example "yarn install"

**Comment by Jao8** [comment]
Yeah, it worked. Thank you very much. 

If possible, can you change the Readme? the instructions there are pointing to npm.
