### ISSUE TITLE
dl.cattr.app  Invalid SSL certificate 

### ISSUE THREAD

**Issue by andrsharov** [cattr-app/desktop-application#92]
Hello! 

Cattr Windows version 2.7.0-prerelease
Cattr Ubuntu version 2.7.0-68

Yesterday(2024.09.25) all desktop application were working. Today (2024.09.26) all desktop applications have stopped.  
It looks like an infinite load. 

![image (63)](https://github.com/user-attachments/assets/7fa26b81-0fff-414f-963f-96fe85b709fe)

I did a little research, and concluded what’s wrong with the URL  https://dl.cattr.app/manifests//release-linux.json  

The application tries endlessly to connect to this URL . But certificate is incorrect . 

![image (62)](https://github.com/user-attachments/assets/baad9efd-88e2-416b-b4b9-76ca6d9abf52)

[at.2024-09-26T08-28-50.465Z.log](https://github.com/user-attachments/files/17145937/at.2024-09-26T08-28-50.465Z.log)

[scope_v2.json](https://github.com/user-attachments/files/17145954/scope_v2.json)

**Comment by alexey87100** [comment]
same problem

**Comment by vadimxoroshilov** [comment]
![Снимок экрана 2024-09-26 в 12 50 31](https://github.com/user-attachments/assets/dcf57010-19b2-4ba9-a72a-4ec0f49ee4db)
Same problem!

**Comment by DanilShapilov** [comment]
[dl](https://dl.cattr.app/manifests/release-linux.json) is up thanks to @vermorag
Can you please check if problem is resolved? @andrsharov @alexey87100 @vadimxoroshilov

**Comment by andrsharov** [comment]
Cattr Windows version 2.7.0-prerelease   -  Works Good! 
Cattr Ubuntu version 2.7.0-68  -  Works Good!

**Comment by vadimxoroshilov** [comment]
2.6.4 version started to work on macOS 12.7.4. Thanks!

**Comment by vermorag** [comment]
Hello.
stats.cattr.app and dl.cattr.app, that used by cattr clients pior to 3.0.0 are now up and running.

**Comment by vadimxoroshilov** [comment]
@vermorag @DanilShapilov 
Hello! The problem has returned, not sure if for the same reasons, but the result is the same: looks like infinite load
![Снимок экрана 2024-09-30 в 09 22 25](https://github.com/user-attachments/assets/42b9a7e3-63f5-4dcb-8a4c-cc40b02af7c7)

**Comment by alexey87100** [comment]
I confirm the problem. Perhaps the reason is that https://stats.cattr.app/ is not working

![изображение](https://github.com/user-attachments/assets/619dcada-0b34-41e6-910d-b5d450508bc9)

But there is nothing strange in the logs:

![изображение](https://github.com/user-attachments/assets/c9ff5169-836e-4b64-a97b-8c72028da9fe)


version 2.7

**Comment by DanilShapilov** [comment]
@alexey87100 @vadimxoroshilov Sorry for the inconvenience. Should work now, please check.

**Comment by andrsharov** [comment]
It works, thanks guys.

**Comment by vadimxoroshilov** [comment]
Works fine, thank you!

**Comment by vadimxoroshilov** [comment]
@vermorag @DanilShapilov
Hello! The problem has returned, not sure if for the same reasons, but the result is the same: looks like infinite load
![изображение](https://github.com/user-attachments/assets/4738b23f-0ff9-4f93-8cf5-170c04ba51ef)
